### ISSUE TITLE
CARDANO_NODE_SOCKET_TCP_HOST

### ISSUE THREAD

**Issue by tokenstakepool** [blinklabs-io/tx-submit-api#138]
Hi, this is not an issue. I'm new to cardano-submit-api.

Managed to download config from cardano-node repo.

[cardano-tx-submit:Info:11] [2023-09-21 10:09:10.41 UTC] Running server on 127.0.0.1:8090

How can I expose it so that I can use my node externally on Eternl or Nami?

Thank you

**Comment by wolf31o2** [comment]
This repository is not about IOG's cardano-submit-api and is a complete replacement.

**Comment by wolf31o2** [comment]
Reaching out via Twitter/X
