### ISSUE TITLE
Cardano node connection pooling

### ISSUE THREAD

**Issue by agaffney** [blinklabs-io/tx-submit-api#4]
Maintain a configurable number of connections to the backend Cardano node to allow reuse for faster transaction submission time. We probably need some health checks for each connection and a configurable idle timeout.

**Comment by wolf31o2** [comment]
I guess we don't need a pool, but simply to implement a persistent connection to the node.

**Comment by wolf31o2** [comment]
Upon further consideration, the existing methodology is probably the best.
